'use strict';

const MidtermCore = (() => {
  function shuffle(items) {
    const a=items.slice();
    for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}
    return a;
  }
  function number(value) {
    const text=String(value??'').trim();
    if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(text))return null;
    const n=Number(text);return Number.isFinite(n)?n:null;
  }
  function answered(q,a) {
    if(q.type==='inline')return Array.isArray(a)&&a.length===q.blanks.length&&a.every(x=>x!==''&&x!==null);
    if(q.type==='mcq')return Number.isInteger(a)&&a>=0&&a<q.opts.length;
    return typeof a==='string'&&a.trim()!=='';
  }
  function grade(q,a) {
    if(q.removed||q.referenceOnly||q.type==='open')return null;
    if(!answered(q,a))return false;
    if(q.type==='mcq')return a===q.ans;
    if(q.type==='inline')return a.every((x,i)=>String(x)===String(q.blanks[i].ans));
    const n=number(a), target=number(q.answer);
    return n!==null&&target!==null&&Math.abs(n-target)<.005000001;
  }
  function potentialDraw(bank,source,target) {
    const eligible=bank.filter(q=>q.source===source&&q.sim&&!q.removed&&!q.referenceOnly);
    const units=new Map();
    eligible.forEach(q=>{const key=q.group||q.id;if(!units.has(key))units.set(key,[]);units.get(key).push(q);});
    let chosen=[];
    for(const unit of shuffle([...units.values()]))if(chosen.length+unit.length<=target)chosen.push(...unit.sort((a,b)=>a.groupOrder-b.groupOrder));
    if(chosen.length!==target)throw new Error('Not enough potential questions');
    return chosen.map(q=>({id:q.id,pts:1}));
  }
  function simulation(bank) {
    const potential=[...potentialDraw(bank,'potential14',13),...potentialDraw(bank,'potential5',12)];
    const other=[...shuffle(bank.filter(q=>q.sim&&q.category==='ayn'&&q.type==='mcq')).slice(0,4),...shuffle(bank.filter(q=>q.sim&&q.category==='ps'&&q.type==='mcq')).slice(0,5),...shuffle(bank.filter(q=>q.sim&&q.category==='old'&&q.type==='mcq'&&!q.referenceOnly)).slice(0,10)].map(q=>({id:q.id,pts:1}));
    const essays=shuffle(bank.filter(q=>q.category==='old'&&q.type==='open'&&q.pts===3)).slice(0,2).map(q=>({id:q.id,pts:3}));
    if(other.length!==19||essays.length!==2)throw new Error('Incomplete simulation bank');
    return [...potential,...other,...essays];
  }
  function filterQuestions(qs,filter) {
    return qs.filter(q=>(!filter.chapter||filter.chapter==='all'||q.chapters?.includes(Number(filter.chapter)))&&(!filter.category||filter.category==='all'||q.category===filter.category)&&(!filter.source||filter.source==='all'||q.source===filter.source));
  }
  return {shuffle,number,answered,grade,potentialDraw,simulation,filterQuestions};
})();
if(typeof module!=='undefined')module.exports=MidtermCore;

if(typeof document!=='undefined'){
const DATA=window.MIDTERM_DATA, bank=DATA.bank, byId=new Map(bank.map(q=>[q.id,q]));
const sourceById=new Map(DATA.sources.map(s=>[s.id,s]));
const CHAPTERS=[[1,'Introduction'],[2,'Measurement'],[3,'Data, cycles and production'],[4,'Household and firm'],[5,'General equilibrium']];
const KEYS={stats:'econ302_stats',history:'econ302_weak_history',review:'econ302_midterm_review',session:'econ302_midterm_session',prefs:'econ302_midterm_preferences'};
const app=document.getElementById('app');
let view='home',filter={chapter:'all',category:'all',source:'all',search:''},page=0,session=null,tick=null;
const memory={};
let storageFailed=false;
let mathContext=null;
function read(key){if(storageFailed&&Object.hasOwn(memory,key))return memory[key];try{const data=JSON.parse(localStorage.getItem(key)||'{}');return data&&typeof data==='object'&&!Array.isArray(data)?data:{};}catch(e){storageFailed=true;return memory[key]||{};}}
function write(key,data){memory[key]=data;try{localStorage.setItem(key,JSON.stringify(data));}catch(e){storageFailed=true;document.getElementById('storage-warning').hidden=false;}}
function finite(n){return Number.isFinite(Number(n))&&Number(n)>0?Number(n):0;}
function ask(text){const d=document.getElementById('confirm-dialog');if(d.open)return Promise.resolve(false);document.getElementById('confirm-message').textContent=text;d.returnValue='cancel';return new Promise(resolve=>{d.addEventListener('close',()=>resolve(d.returnValue==='ok'),{once:true});d.showModal();});}
function applyMathContext(p){
 if(!p||!['log','ql'].every(k=>p[k]&&['a','b','w','h'].every(x=>Number.isFinite(p[k][x])&&p[k][x]>0)))return;
 const L=p.log,Q=p.ql;if(Q.b/(Q.a*Q.w)>=Q.h)return;
 mathContext=p;
 for(const [id,k] of [['c5p1_1','log'],['c5p1_2','ql']]){
  const x=p[k],l=k==='log'?x.b*x.h/(x.a+x.b):x.b/(x.a*x.w),N=x.h-l,C=x.w*N;
  bank.filter(q=>q.group===id).forEach(q=>{q.scenario=`Shared household: U=${x.a}${k==='log'?' ln C':' C'}+${x.b} ln l; C=w(1−t)(h−l). a=${x.a}, b=${x.b}, w(1−t)=${x.w}, h=${x.h}. Practice values match the Chapter 5 page.`;if(q.type==='fill'){q.answer=C.toFixed(2);q.note=`<strong>Đáp án: ${C.toFixed(2)}</strong><br>MU_C=${k==='log'?'a/C':'a'}, MU_l=b/l. MRS=${k==='log'?'bC/(al)':'b/(al)'}=w(1−t)=${x.w}.<br>${k==='log'?'Thế C=W(h−l) rồi chia W: b(h−l)=al ⇒ l=bh/(a+b).':'Nhân chéo: b=a·l·W ⇒ l=b/(aW).'}<br>l=${l.toFixed(2)}, N=h−l=${N.toFixed(2)}, C=W×N=${C.toFixed(2)}.<br>${k==='log'?'Full log earnings-only: W tăng thì l,N không đổi; C tăng. IE và SE bằng độ lớn, trái dấu.':'Quasi-linear C, nghiệm nội: W tăng ⇒ l giảm, N và C tăng. IE trên leisure bằng 0.'}<br>Giữ w(1−t) nguyên cụm. Không nhân wage với leisure.`;}});
 }
}
function history(){const h=read(KEYS.history),stats=read(KEYS.stats);for(const [id,s] of Object.entries(stats)){if(!s||typeof s!=='object')continue;if(!h[id]&&finite(s.attempts)>0)h[id]={attempts:finite(s.attempts),correct:finite(s.correct),wrong:Math.max(0,finite(s.attempts)-finite(s.correct))};}return h;}
function missed(q){const h=history()[q.id],s=read(KEYS.stats)[q.id];return !q.removed&&!q.referenceOnly&&!(s&&s.clearedFromMistakes)&&(finite(h&&h.wrong)>0||!!(s&&s.everWrong));}
function record(q,ok,a,attemptToken){const h=history(),s=read(KEYS.stats);if(attemptToken&&(s[q.id]?.lastAttemptToken===attemptToken||h[q.id]?.lastAttemptToken===attemptToken))return;const prev=h[q.id]||{};h[q.id]={...prev,attempts:finite(prev.attempts)+1,correct:finite(prev.correct)+(ok?1:0),wrong:finite(prev.wrong)+(ok?0:1)};if(!ok)h[q.id].lastWrongAnswer=a;const old=s[q.id]||{};s[q.id]={...old,attempts:finite(old.attempts)+1,correct:finite(old.correct)+(ok?1:0),lastResult:ok?'correct':'incorrect',lastAnswer:a,lastAnswerKey:q.type==='fill'?q.answer:null,everWrong:!!old.everWrong||!ok,clearedFromMistakes:ok?!!old.clearedFromMistakes:false};if(attemptToken){h[q.id].lastAttemptToken=attemptToken;s[q.id].lastAttemptToken=attemptToken;}write(KEYS.history,h);write(KEYS.stats,s);updateBadge();}
function e(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function markup(q,text){return q.category==='potential'?String(text||''):e(text);}
function title(q){return sourceById.get(q.source)?.title||q.source;}
function automatic(q){return !q.removed&&!q.referenceOnly&&q.type!=='open';}
function progress(qs){const stats=read(KEYS.stats),active=qs.filter(automatic);const correct=active.filter(q=>stats[q.id]?.lastResult==='correct').length;return {correct,total:active.length,percent:active.length?Math.round(100*correct/active.length):0};}
function updateBadge(){document.getElementById('miss-count').textContent=bank.filter(missed).length;}
function sourceLinks(q){const s=sourceById.get(q.source);if(!s)return '';let links=(s.files||[]).map(f=>`<a href="${e(encodeURI(f.url))}${q.page&&f.name.endsWith('.pdf')?'#page='+q.page:''}" target="_blank" rel="noopener">${e(f.name)}</a>`);if(s.canvas)links.push(`<a href="${e(s.canvas)}" target="_blank" rel="noopener">Canvas source</a>`);if(s.video)links.push(`<a href="${e(s.video)}" target="_blank" rel="noopener">Official answer video</a>`);return links.length?`<details class="question-links"><summary>Nguồn câu hỏi và đáp án</summary>${links.join('<br>')}</details>`:'';}
function provenance(q){if(q.removed)return 'Cô đã bỏ';if(q.referenceOnly)return 'Historical reference';if(q.verified==='ai-checked')return 'AI generated, model checked';if(q.verified==='derived')return 'Model-derived guide';if(q.verified==='discussion')return 'Survey, không chấm';if(q.verified==='checked')return 'Đã đối chiếu bài Canvas';if(q.verified==='official-rubric')return 'Official rubric, tự đánh giá';return 'Official answer key';}
function correctText(q){if(q.type==='mcq')return `${String.fromCharCode(65+q.ans)}. ${markup(q,q.opts[q.ans])}`;if(q.type==='inline')return q.blanks.map((b,i)=>`Blank ${i+1}: ${e(b.opts[b.ans])}`).join('<br>');return e(q.answer);}
function feedback(q,r,pts){
 if(!r)return '';
 if(r.skipped)return '<div class="feedback"><strong>Hết giờ, chưa trả lời.</strong><p>Câu này không được ghi là lỗi sai. Bốc câu tiếp để làm lại.</p></div>';
 if(q.removed||q.referenceOnly)return `<div class="feedback"><strong>${q.removed?'Câu đã bỏ':'Key lịch sử, không chấm hiện tại'}</strong>${q.type==='mcq'?'<p>'+correctText(q)+'</p>':''}<div class="note">${markup(q,q.note)}</div></div>`;
 if(q.type==='open')return `<div class="feedback"><strong>Hướng dẫn và tiêu chí tự đánh giá</strong><div class="note">${markup(q,q.note)}</div>${q.verified==='discussion'?'':`<div class="mark-self"><label>Tự chấm theo rubric: <select data-self="${q.id}"><option value="">Chưa chấm</option>${Array.from({length:pts+1},(_,i)=>`<option value="${i}" ${r.self===i?'selected':''}>${i}/${pts}</option>`).join('')}</select></label><p class="muted">Điểm do bạn tự đánh giá, không phải AI tự xác nhận bài viết đúng.</p></div>`}</div>`;
 const parts=q.type==='inline'?q.blanks.map((b,i)=>`<p>${String(r.answer?.[i])===String(b.ans)?'✓':'✗'} Blank ${i+1}. Bạn chọn: ${r.answer?.[i]!==''&&r.answer?.[i]!=null?e(b.opts[Number(r.answer[i])]):'Chưa chọn'}. Đáp án: ${e(b.opts[b.ans])}.</p>`).join(''):'';
 return `<div class="feedback ${r.ok?'ok':'err'}"><strong>${r.ok?'✓ Đúng':'✗ Sai hoặc chưa trả lời'}</strong><p>Đáp án: ${correctText(q)}</p>${parts}<div class="note">${markup(q,q.note)}</div></div>`;
}
function card(q,index,mode,answer,result,pts=q.pts||1){
 const timed=mode==='session'&&!session.submitted,locked=!!result||q.removed||q.referenceOnly;
 let inputs='',stem=markup(q,q.stem);
 if(q.type==='mcq')inputs=`<div class="choices">${q.opts.map((opt,i)=>`<label class="${result&&!q.referenceOnly&&i===q.ans?'answer':result&&answer===i&&i!==q.ans?'wrong':''}"><input type="radio" name="${q.id}" value="${i}" ${answer===i?'checked':''} ${locked?'disabled':''}><span>${String.fromCharCode(65+i)}. ${markup(q,opt)}</span></label>`).join('')}</div>`;
 else if(q.type==='inline'){let n=0;stem=stem.replace(/____/g,()=>{const i=n++,b=q.blanks[i];if(!b)return '____';return `<select aria-label="Blank ${i+1}" data-blank="${i}" ${locked?'disabled':''}><option value="">Select</option>${b.opts.map((o,j)=>`<option value="${j}" ${String(answer?.[i])===String(j)?'selected':''}>${e(o)}</option>`).join('')}</select>`;});}
 else if(q.type==='fill')inputs=`<label>Answer <input aria-label="Answer" class="numeric" type="text" inputmode="decimal" value="${e(answer||'')}" ${locked?'disabled':''} placeholder="Two decimal places"></label>`;
 else inputs=`<label class="muted">Viết câu trả lời trước khi xem hướng dẫn<textarea aria-label="Written answer" ${result?'disabled':''} placeholder="Your explanation / calculations">${e(answer||'')}</textarea></label>`;
 return `<article class="card ${result&&automatic(q)?result.ok?'correct':'incorrect':''}" id="q-${q.id}" data-q="${q.id}"><div class="card-head"><span>${index+1}. ${e(title(q))}${q.partLabel?' | PART '+e(q.partLabel):''}</span><span class="badge chapter">${q.chapters?.length?'Chapter '+q.chapters.join(', '):'Exam instructions'}</span><span class="badge ${q.category==='ai'?'ai':q.verified==='official'?'official':''}">${e(provenance(q))}</span><span>${q.verified==='discussion'?'Ungraded':q.category==='more'?'Self-check':pts+' pt'+(pts>1?'s':'')}</span>${timed?`<button class="flag ${session.flags[q.id]?'active':''}" data-flag="${q.id}" aria-pressed="${!!session.flags[q.id]}">Flag</button>`:''}</div>${q.image?`<img class="source-image" src="${e(q.image)}" alt="${e(q.imageAlt)}" loading="lazy">`:''}${q.scenario?`<div class="scenario">${markup(q,q.scenario)}</div>`:''}${q.warning?`<p class="warning">${e(q.warning)}</p>`:''}<div class="stem">${stem}</div>${inputs}${mode!=='session'?`<div class="actions">${result?automatic(q)||q.type==='open'?`<button class="btn small secondary" data-retry="${q.id}">Làm lại</button>`:'':`<button class="btn small" data-check="${q.id}">${q.removed||q.referenceOnly?'Xem key và ghi chú':q.type==='open'?'Xem rubric':'Check answer'}</button>`}</div>`:''}${feedback(q,result,pts)}${sourceLinks(q)}</article>`;
}
function getAnswer(q,el){if(q.type==='mcq'){const a=el.querySelector('input:checked');return a?Number(a.value):null;}if(q.type==='inline')return [...el.querySelectorAll('[data-blank]')].map(s=>s.value);return el.querySelector('input,textarea')?.value||'';}
function saveInput(id){const q=byId.get(id),el=document.querySelector(`[data-q="${id}"]`);if(!q||!el)return;const a=getAnswer(q,el);if(view==='session'&&session&&!session.submitted){session.answers[id]=a;saveSession();updateQnav();}else{const state=read(KEYS.review);state[id]={...(state[id]||{}),answer:a,mathSig:q.group?JSON.stringify(mathContext):null};write(KEYS.review,state);}}
function scopeQuestions(){let qs=bank.filter(q=>!q.removed);if(view==='ai')return qs.filter(q=>q.category==='ai');if(view==='mistakes')return qs.filter(missed).sort((a,b)=>finite(history()[b.id]?.wrong)-finite(history()[a.id]?.wrong));return qs.filter(q=>q.category!=='ai');}
function availableSources(){const ids=new Set(MidtermCore.filterQuestions(scopeQuestions(),{...filter,source:'all'}).map(q=>q.source));return DATA.sources.filter(s=>!s.tba&&ids.has(s.id));}
function selectQuestions(){let qs=MidtermCore.filterQuestions(scopeQuestions(),filter);if(filter.search.trim()){const term=filter.search.toLowerCase();qs=qs.filter(q=>(q.stem+' '+q.scenario+' '+q.tag+' '+title(q)).toLowerCase().includes(term));}return qs;}
function renderLibrary(){if(filter.source!=='all'&&!availableSources().some(s=>s.id===filter.source))filter.source='all';const qs=selectQuestions(),p=progress(qs),state=read(KEYS.review);const pages=Math.max(1,Math.ceil(qs.length/12));page=Math.min(page,pages-1);write(KEYS.prefs,{view,filter,page});let html=`<div class="section-top"><div><p class="kicker">${view==='ai'?'AI generated, model checked':'Midterm 1 practice'}</p><h1>${view==='mistakes'?'Những câu từng làm sai':view==='ai'?'Extended AI Questions':'Luyện theo nguồn'}</h1></div><button class="btn small secondary" data-refresh>Refresh</button></div><p class="muted">${view==='mistakes'?'Câu sai vẫn ở đây sau khi làm lại đúng. Chỉ xóa khi bạn chủ động xác nhận.':view==='ai'?'Câu mới dựa trên concepts của cô, đổi số hoặc cách hỏi. Không phải potential questions chính thức và không nằm trong simulation.':'Questions in English, lời giải từng bước bằng tiếng Việt. Câu tự luận có rubric để tự chấm.'}</p>`;
 html+=`<div class="filters"><label class="search-field">Tìm câu hỏi<input id="search" aria-label="Search questions" placeholder="Search topic or question" value="${e(filter.search)}"></label><button class="btn small secondary" data-search>Search</button><label>Chapter<select id="chapter" aria-label="Chapter"><option value="all">All chapters</option>${CHAPTERS.map(([n,name])=>`<option value="${n}" ${filter.chapter===String(n)?'selected':''}>Chapter ${n}: ${name}</option>`).join('')}</select></label><label>Loại câu<select id="category" aria-label="Category"><option value="all">All categories</option>${[['potential','Potential quiz'],['ayn','Ask Your Neighbor'],['ps','Problem Sets'],['more','More Practice'],['old','Old Midterm 1'],['ai','Extended AI']].map(([id,name])=>`<option value="${id}" ${filter.category===id?'selected':''}>${name}</option>`).join('')}</select></label><label class="source-field">Nguồn<select id="source" aria-label="Source"><option value="all">All sources</option>${availableSources().map(s=>`<option value="${s.id}" ${filter.source===s.id?'selected':''}>${e(s.title)}</option>`).join('')}</select></label></div><p class="muted">${qs.length} cards | ${p.correct}/${p.total} objective questions correct. Essay scores are separate.</p><div class="progress"><span style="width:${p.percent}%"></span></div>`;
 if(view==='mistakes')html+='<button class="btn small secondary" data-clear-mistakes>Xóa danh sách này có xác nhận</button>';
 if(!qs.length)html+='<div class="empty">Chưa có câu phù hợp với chapter và nguồn đang chọn. Chọn All chapters hoặc All sources để xem thêm.</div>';
 qs.slice(page*12,(page+1)*12).forEach((q,i)=>{const saved=state[q.id];const r=q.group&&saved?.mathSig!==JSON.stringify(mathContext)?null:saved;html+=card(q,page*12+i,'review',r?.answer,r?.result);});
 html+=`<div class="pager"><button class="btn small secondary" data-page="${page-1}" ${page===0?'disabled':''}>Previous</button><span>${page+1}/${pages}</span><button class="btn small secondary" data-page="${page+1}" ${page+1>=pages?'disabled':''}>Next</button></div>`;app.innerHTML=html;
}
function home(){const originals=bank.filter(q=>q.category!=='ai'),p=progress(originals);const misses=bank.filter(missed).length;let html=`<section class="hero"><p class="kicker">Module 1 | Chapters 1 to 5</p><h1>Ôn đúng nguồn.<br>Hiểu vì sao đúng.</h1><p>Luyện câu gốc, theo dõi câu từng sai, rồi thử câu đổi cách hỏi. Midterm simulation có 50 điểm và 60 phút: 25 điểm potential quiz, 19 điểm trắc nghiệm liên quan và 6 điểm tự luận tự chấm.</p><div class="actions"><button class="btn" data-start="simulation">Start Midterm Simulation</button><button class="btn secondary" data-start="gacha">Gacha: 1 câu, 1 phút</button>${session?'<button class="btn secondary" data-resume>Xem bài đã lưu</button>':''}</div><p class="muted" style="margin-top:14px">Mô phỏng để ôn, không phải bản đoán đề thi. Ít nhất 50% điểm lấy từ potential quiz. Câu cô bỏ, câu lịch sử mơ hồ và AI không được bốc vào simulation.</p></section><div class="stats"><div class="stat"><strong>${p.correct}/${p.total}</strong>Objective progress</div><div class="stat"><strong>${misses}</strong>Từng làm sai</div><div class="stat"><strong>60 phút</strong>Midterm simulation</div></div>`;
 const cats=[['potential','Potential Quiz Questions','Tái sử dụng câu và ID có sẵn của Chapters 1 to 4 và Chapter 5.'],['ayn','Ask Your Neighbor','Câu thảo luận trên lớp, official answer keys và survey riêng.'],['ps','Problem Sets','Các bài bạn đã cung cấp. Bài chưa có hiển thị TBA.'],['more','More Practice','Câu tính toán và graph, model-derived guides cùng official video links.'],['old','Old Midterm 1','2016, 2017, 2019: toàn bộ MCQ và các phần short answer.'],['ai','Extended AI Questions','Câu luyện mới, thay số và wording dựa trên nguồn của cô.']];
 html+='<div class="grid">'+cats.map(([id,name,desc])=>{const qs=bank.filter(q=>q.category===id&&!q.removed),p=progress(qs);return `<section class="tile"><h2>${name}</h2><p>${desc}</p><p class="muted">${qs.length} cards | ${p.correct}/${p.total} objective correct</p><div class="actions"><button class="btn small" data-browse="${id}">Open</button></div></section>`;}).join('')+'</div><div class="panel"><h2>Nhớ trước khi bấm đáp án</h2><p><strong>l*</strong> là giờ nghỉ chọn ở điểm tối ưu. <strong>l_max</strong> là giao trục PPF khi C=0: zF(K,h−l_max)=G. Preferences đổi choice, không đổi PPF.</p><p><strong>T</strong> là khoản thuế cố định, trực tiếp pure IE. <strong>t</strong> là tỷ lệ thuế wage, đổi W=w(1−t), có IE và SE. G unproductive khác G làm z tăng.</p><p class="muted">Cache lưu trong trình duyệt này. Commit hoặc cập nhật website không tự xóa cache. Refresh có xác nhận, reset tiến độ trong phạm vi đang xem, giữ lịch sử câu sai.</p></div>';app.innerHTML=html;}
function sources(){let html='<p class="kicker">Source library</p><h1>Tài liệu Midterm 1</h1><p>Các nguồn đã tải được chia đúng nhóm. Original problem-set captures giữ ở máy; trang chỉ chứa câu và lời giải, không chứa lịch sử điểm hoặc bài nộp của bạn.</p><div class="grid">';for(const s of DATA.sources){const qs=bank.filter(q=>q.source===s.id&&!q.removed);html+=`<section class="tile"><h3>${e(s.title)} ${s.tba?'<span class="badge tba">TBA</span>':''}</h3><p class="muted">${s.tba?'Chờ tài liệu/câu trả lời. Chưa đưa vào simulation.':qs.length+' cards. '+(s.category==='more'?'Guide từ model, video chính thức mở ở link bên dưới.':'') }</p>${s.tba?'':`<div class="actions"><button class="btn small" data-source="${s.id}">Review</button>${qs.some(automatic)?`<button class="btn small secondary" data-practice="${s.id}">Timed practice</button>`:''}</div>`}${s.canvas?`<a href="${e(s.canvas)}" target="_blank" rel="noopener">Open in Canvas</a>`:''}${s.video?`<a href="${e(s.video)}" target="_blank" rel="noopener">Official answer video</a>`:''}<details><summary>Files and keys</summary><ul class="source-list">${(s.files||[]).map(f=>`<li><a href="${e(encodeURI(f.url))}" target="_blank" rel="noopener">${e(f.name)}</a></li>`).join('')||'<li>Questions and explanations are available in the practice bank.</li>'}</ul></details></section>`;}html+='</div><div class="warning">More Practice videos: giữ đường dẫn chính thức; chưa tải được file video hoặc transcript từ player. Hướng dẫn trên trang được giải theo model, không gắn nhãn đã đối chiếu video.</div>';
 for(const category of ['Lecture References','Textbook Practice','Potential Quiz Questions']){const files=DATA.catalog.filter(f=>f.category===category);html+=`<details class="panel" style="margin-bottom:14px"><summary>${e(category)} (${files.length} files)</summary><ul class="source-list">${files.map(f=>`<li><a href="${e(encodeURI(f.url))}" target="_blank" rel="noopener">${e(f.name)}</a></li>`).join('')}</ul></details>`;}
 html+='<div class="panel"><h2>Instructor exclusions</h2><p>Chapters 1 to 4: Pool 2 Question 16. Chapter 5: Pool 6 Question 6 và Pool 7 Question 12. Giữ bản nguồn, không bốc các câu này vào bài chấm điểm.</p><a href="https://canvas.wisc.edu/courses/514581/discussion_topics/2536706" target="_blank" rel="noopener">Chapter 5 announcement</a></div>';app.innerHTML=html;
}
function setView(next){view=next;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));updateBadge();if(view==='home')home();else if(view==='sources')sources();else if(view==='session')renderSession();else renderLibrary();location.hash=view;}
function saveSession(){if(session)write(KEYS.session,session);}
async function abandon(){if(!session)return true;if(!session.submitted&&!(await ask('Thoát bài đang làm? Câu chưa nộp sẽ không được tính là lỗi sai.')))return false;session=null;clearInterval(tick);write(KEYS.session,{});document.getElementById('clock').hidden=true;return true;}
async function start(mode,source){if(session&&!(await abandon()))return;let items;if(mode==='simulation')items=MidtermCore.simulation(bank);else if(mode==='gacha'){const q=MidtermCore.shuffle(bank.filter(q=>automatic(q)&&q.category!=='ai'))[0];items=[{id:q.id,pts:1}];}else items=bank.filter(q=>q.source===source&&automatic(q)).map(q=>({id:q.id,pts:q.pts||1}));if(!items.length)return;session={version:DATA.version,token:Date.now()+'-'+Math.random().toString(36).slice(2),mode,source,items,answers:{},results:{},flags:{},submitted:false,mathContext,deadline:Date.now()+(mode==='simulation'?3600:mode==='gacha'?60:70*items.length)*1000};saveSession();setView('session');startClock();window.scrollTo(0,0);}
function updateQnav(){if(!session)return;app.querySelectorAll('[data-nav-q]').forEach(a=>{const id=a.dataset.navQ;a.classList.toggle('done',MidtermCore.answered(byId.get(id),session.answers[id]));a.classList.toggle('flagged',!!session.flags[id]);});}
function renderSession(){if(!session){setView('home');return;}const pts=session.items.reduce((n,x)=>n+x.pts,0),autoPts=session.items.filter(x=>automatic(byId.get(x.id))).reduce((n,x)=>n+x.pts,0);let html=`<div class="section-top"><div><p class="kicker">${session.mode==='simulation'?'50 points | 60 minutes':session.mode==='gacha'?'Gacha | 60 seconds':'70 seconds per objective question'}</p><h1>${session.mode==='simulation'?'Midterm Simulation':session.mode==='gacha'?'Gacha':'Timed Practice'}</h1></div></div>`;
 if(session.submitted){let score=0,pending=0;session.items.forEach(x=>{const q=byId.get(x.id),r=session.results[x.id];if(q.type==='open'){if(r?.self==null&&MidtermCore.answered(q,session.answers[x.id]))pending+=x.pts;else score+=Math.min(x.pts,finite(r?.self));}else if(r?.ok)score+=x.pts;});html+=`<section class="hero"><h2>${pending?score+' điểm đã chấm, '+pending+' điểm tự luận chờ tự chấm':score+'/'+pts+' điểm'}</h2><p>Trắc nghiệm chấm tự động (${autoPts} điểm tối đa). Tự luận đánh giá theo rubric; tự chấm không phải đáp án được máy xác nhận.</p><div class="actions"><button class="btn" data-start="${session.mode}" ${session.source?'data-practice-source="'+e(session.source)+'"':''}>${session.mode==='gacha'?'Bốc câu tiếp':'Làm bài mới'}</button><button class="btn secondary" data-view="mistakes">Xem Mistakes</button></div></section>`;}
 html+='<div class="qnav">'+session.items.map((x,i)=>`<a href="#q-${x.id}" data-nav-q="${x.id}">${i+1}</a>`).join('')+'</div>';
 session.items.forEach((x,i)=>{const q=byId.get(x.id);html+=card(q,i,'session',session.answers[x.id],session.results[x.id],x.pts);});if(!session.submitted)html+='<button class="btn" data-submit>Nộp bài</button>';app.innerHTML=html;updateQnav();document.getElementById('clock').hidden=session.submitted;}
async function submit(expired=false){if(!session||session.submitted)return;const cached=read(KEYS.session);if(cached.token===session.token&&cached.submitted){session=cached;clearInterval(tick);setView('session');return;}if(cached.token&&cached.token!==session.token){session=null;clearInterval(tick);document.getElementById('clock').hidden=true;setView('home');return;}if(!expired&&!(await ask('Nộp bài và xem đáp án? Sau khi nộp không đổi câu trả lời của lần này.')))return;if(!session||session.submitted)return;if(expired&&document.getElementById('confirm-dialog').open)document.getElementById('confirm-dialog').close('cancel');for(const x of session.items){const q=byId.get(x.id),a=session.answers[x.id],has=MidtermCore.answered(q,a);if(session.mode==='gacha'&&!has){session.results[x.id]={skipped:true};continue;}const ok=MidtermCore.grade(q,a);session.results[x.id]={answer:a,ok,...(q.type==='open'&&!has?{self:0}:{})};}session.submitted=true;saveSession();clearInterval(tick);for(const x of session.items){const q=byId.get(x.id),r=session.results[x.id];if(automatic(q)&&!r.skipped)record(q,r.ok,r.answer,session.token);}setView('session');document.getElementById('clock').hidden=true;}
function startClock(){clearInterval(tick);const update=()=>{if(!session||session.submitted){clearInterval(tick);return;}const left=Math.max(0,Math.ceil((session.deadline-Date.now())/1000));document.getElementById('clock-title').textContent=session.mode==='simulation'?'Midterm 1':session.mode==='gacha'?'Gacha':'Timed practice';document.getElementById('clock-time').textContent=Math.floor(left/60)+':'+String(left%60).padStart(2,'0');document.getElementById('clock').classList.toggle('urgent',left<=60);document.getElementById('clock').hidden=false;if(left===0)submit(true);};update();tick=setInterval(update,500);}
app.addEventListener('input',evt=>{const cardEl=evt.target.closest('[data-q]');if(cardEl)saveInput(cardEl.dataset.q);});
app.addEventListener('change',evt=>{const el=evt.target;if(el.id==='chapter'||el.id==='category'||el.id==='source'){filter[el.id]=el.value;if(el.id==='category')filter.source='all';else if(el.id==='source'&&el.value!=='all')filter.category=sourceById.get(el.value)?.category||'all';page=0;if(view!=='mistakes'&&el.id!=='chapter'){if(filter.category==='ai'||filter.source==='ai')view='ai';else if(view==='ai'&&el.value!=='all')view='library';}setView(view);return;}if(el.dataset.self){const id=el.dataset.self;if(el.value==='')return;const n=Number(el.value);if(view==='session'){const pts=session.items.find(x=>x.id===id).pts;session.results[id].self=n;record(byId.get(id),n===pts,session.answers[id]);saveSession();renderSession();}else{const st=read(KEYS.review);st[id].result.self=n;record(byId.get(id),n===(byId.get(id).pts||1),st[id].answer);write(KEYS.review,st);renderLibrary();}return;}const cardEl=el.closest('[data-q]');if(cardEl)saveInput(cardEl.dataset.q);});
app.addEventListener('keydown',evt=>{if(evt.target.id==='search'&&evt.key==='Enter'){filter.search=evt.target.value;page=0;renderLibrary();}});
app.addEventListener('click',async evt=>{const b=evt.target.closest('button');if(!b)return;const d=b.dataset;if(d.view){filter={chapter:'all',category:'all',source:'all',search:''};page=0;setView(d.view);}else if(d.browse){filter={chapter:'all',category:d.browse,source:'all',search:''};page=0;setView(d.browse==='ai'?'ai':'library');}else if(d.source){filter={chapter:'all',category:'all',source:d.source,search:''};page=0;setView('library');}else if(d.start)start(d.start,d.practiceSource);else if(d.practice)start('practice',d.practice);else if('resume'in d){setView('session');startClock();}else if('submit'in d)submit();else if(d.flag){session.flags[d.flag]=!session.flags[d.flag];saveSession();b.classList.toggle('active',!!session.flags[d.flag]);b.setAttribute('aria-pressed',!!session.flags[d.flag]);updateQnav();}else if(d.page!==undefined){page=Number(d.page);renderLibrary();window.scrollTo(0,0);}else if('search'in d){filter.search=document.getElementById('search').value;page=0;renderLibrary();}else if(d.check){const q=byId.get(d.check),el=b.closest('[data-q]'),a=getAnswer(q,el);if(automatic(q)&&!MidtermCore.answered(q,a)){let msg=el.querySelector('.input-warning');if(!msg){msg=document.createElement('p');msg.className='warning input-warning';msg.setAttribute('role','alert');el.append(msg);}msg.textContent='Trả lời đầy đủ trước khi Check answer.';return;}const ok=MidtermCore.grade(q,a),st=read(KEYS.review);st[q.id]={answer:a,result:{answer:a,ok},mathSig:q.group?JSON.stringify(mathContext):null};write(KEYS.review,st);if(automatic(q))record(q,ok,a);renderLibrary();}else if(d.retry){const st=read(KEYS.review);st[d.retry]={answer:st[d.retry]?.answer,mathSig:st[d.retry]?.mathSig};write(KEYS.review,st);renderLibrary();}else if('refresh'in d){if(!(await ask('Reset câu trả lời và thanh tiến độ trong bộ đang xem? Lịch sử từng sai vẫn được giữ.')))return;const qs=selectQuestions(),st=read(KEYS.review),stats=read(KEYS.stats);qs.forEach(q=>{delete st[q.id];delete stats[q.id];});write(KEYS.history,history());write(KEYS.review,st);write(KEYS.stats,stats);renderLibrary();updateBadge();}else if('clearMistakes'in d){if(!(await ask('Ẩn các câu sai trong bộ đang xem khỏi Mistakes? Lịch sử số lần sai vẫn giữ. Chỉ hiện lại khi bạn trả lời sai lần nữa.')))return;const st=read(KEYS.stats);selectQuestions().forEach(q=>{st[q.id]={...(st[q.id]||{}),clearedFromMistakes:true};});write(KEYS.stats,st);renderLibrary();updateBadge();}});
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>{filter={chapter:'all',category:'all',source:'all',search:''};page=0;setView(b.dataset.view);}));
document.getElementById('finish-top').addEventListener('click',()=>submit());
document.getElementById('exit-session').addEventListener('click',async()=>{if(await abandon())setView('home');});
window.addEventListener('storage',evt=>{if(evt.key===KEYS.stats||evt.key===KEYS.history)updateBadge();});
session=read(KEYS.session);
if(!['simulation','gacha','practice'].includes(session.mode)||typeof session.token!=='string'||!session.version||session.version!==DATA.version||!Array.isArray(session.items)||!session.items.length||!session.items.every(x=>x&&typeof x.id==='string'&&Number.isInteger(x.pts)&&x.pts>0&&x.pts<=8&&byId.has(x.id)&&!byId.get(x.id).removed&&!byId.get(x.id).referenceOnly)||!Number.isFinite(session.deadline)||!session.answers||!session.results||!session.flags)session=null;
applyMathContext(session?session.mathContext:read('econ302_math_params'));
const initial=location.hash.slice(1);
const prefs=read(KEYS.prefs);if(['library','ai','mistakes'].includes(initial)&&prefs.view===initial&&prefs.filter&&typeof prefs.filter.search==='string'&&typeof prefs.filter.category==='string'&&typeof prefs.filter.source==='string'){filter={...prefs.filter,chapter:['1','2','3','4','5'].includes(prefs.filter.chapter)?prefs.filter.chapter:'all'};page=Number.isInteger(prefs.page)&&prefs.page>=0?prefs.page:0;}
setView(session&&(!session.submitted||initial==='session'||initial.startsWith('q-'))?'session':['home','library','mistakes','sources','ai'].includes(initial)?initial:'home');
if(session&&!session.submitted)startClock();
}
